development:
  adapter: postgresql
  encoding: unicode
  database: documents_drive_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: documents_drive_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: documents_drive_production
  pool: 5